name: recursion-schemes-playground
version: 0.1.0.0
github: Javran/recursion-schemes-playground
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
description: description

dependencies:
- base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - data-fix
    - free
    - recursion-schemes
    - mtl
    - containers
    - memoize

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - recursion-schemes-playground
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - recursion-schemes-playground
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
