name: kc-sprite-tool
version: 0.1.0.0
github: "Javran/misc"
license: BSD3
author: "Javran Cheng"
maintainer: "javran.c@gmail.com"
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

ghc-options:
  - -Wall

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoUnicodeSyntax
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances


dependencies:
- aeson
- base
- containers
- filepath
- hip
- text
- unordered-containers

executables:
  demo:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
