name: gentoo-package-watcher
version: 0.1.0.0
github: Javran/gentoo-package-watcher
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
description: description

dependencies:
- base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - aeson
    - async
    - bytestring
    - deepseq
    - html-conduit
    - http-client
    - http-client-tls
    - natural-sort
    - safe-exceptions
    - split
    - text
    - unordered-containers
    - xml-conduit

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - gentoo-package-watcher
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - gentoo-package-watcher
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
